version: '3'
services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "hcmut-thesis-controller.com:192.168.49.2"
      - "hcmut-thesis-gateway.com:192.168.49.2"