version: '3'
services:
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "controller-gateway.com:192.168.49.2"
      - "api-gateway.com:192.168.49.2"
      - "front-end.com:192.168.49.2"
    