version: '2'

services:
  rancher:
    image: rancher/rancher:latest
    restart: always
    ports:
    - "8080:80/tcp"
    - "8443:443/tcp"
    environment:
      - HTTP_PROXY="http://localhost/rancher"
      - HTTPS_PROXY="https://localhost/rancher"
    volumes:
    - "rancher-data:/var/lib/rancher"
    privileged: true

volumes:
  rancher-data: