[controller]

[controller.grpc]
port = "5551"

[controller.http]
port = "8080"

[controller.rtsp_relay]
rtsp_relay_ip = "rtsp-server-service" # Don't use localhost
rtsp_relay_port = "8554" # Port for RTSP Server is configured in pkg/rtsp_server_sdk

[log]
level = "info"
filePath= "logs/controller.log"
maxSize=50
maxBackups=10
maxAge=28

[network]
max_bitrate = "4500"
min_bitrate = "128"
twcc_interval = "100" #Miliseconds

[redis]
# address = "0.0.0.0:6379"
address = "redis-service:6379"
# Split address by COMMA, Example: address = "0.0.0.0:6379, 0.0.0.0:6379"
database = "0"
is_cluster = "false"
password = ""

[uploader]
credentials="/configs/google-service-account.json"
destination="1ObING3lxYLZRPyi5u7yyKDPUA6rJqq3E"

[recorder]
max_record_files = "15"
record_file_duration = "10" # In seconds