[server]
    [server.http]
        host = "http://localhost"
        port = "3001"

[api_server]
    [api_server.grpc]
        host = "node-api-server"
        port = "50051"
    [api_server.http]
        scheme = "http"
        host = "node-api-server"
        port = "3000"
