apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/dathuynh/hcmut-thesis-deploy/configs
