apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hcmut-thesis-controller.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: controller-service
                port:
                  number: 8080
    - host: hcmut-thesis-gateway.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-api-server
                port:
                  number: 8080
       