apiVersion: v1
kind: Service
metadata:
  name: ion-sfu-service
spec:
  selector:
    app: ion-sfu
  ports:
    - name: icemux-tcp
      protocol:  TCP
      port: 5001
      targetPort: 5001
    - name: icemux-udp
      protocol:  UDP
      port: 5000
      targetPort: 5000
    # - name: grpc
    #   port: 5551
    #   targetPort: grpc
    # - name: jsonrpc
    #   port: 7000
    #   targetPort: jsonrpc
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ion-sfu-deployment
  labels:
    app: ion-sfu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ion-sfu
  template:
    metadata:
      labels:
        app: ion-sfu
    spec:
      containers:
      - name: ion-sfu
        image: huynhthanhdat1108/ion-sfu:latest
        ports:
          - containerPort: 5000
            protocol: UDP
          - containerPort: 5001
            protocol: TCP
          # - name: grpc
          #   containerPort: 5551
          # - name: jsonrpc
          #   containerPort: 7000
          # - name: metrics
          #   containerPort: 9123
        volumeMounts:
          - name: config-files
            mountPath: /configs
            readOnly: true
      volumes:
        - name: config-files
          configMap:
            name: config-files
            items:
              - key: sfu.toml
                path: sfu.toml
