apiVersion: v1
kind: Pod
metadata:
  name: test-config
spec:
  containers:
  - name: test-config
    image: huynhthanhdat1108/node-api-server:latest
    command: ['sleep', 'infinity']
    env:
      - name: CONFIG_PATH
        value: /configs/node-api-server.toml
    volumeMounts:
          - name: config-files
            mountPath: /configs
            readOnly: true
  volumes:
    - name: config-files
      configMap:
        name: config-files
        items:
          - key: node-api-server.toml
            path: node-api-server.toml