apiVersion: v1
kind: Pod
metadata:
  name: test-config
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
          - name: config-files
            mountPath: /configs
            readOnly: true
  volumes:
    - name: config-files
      configMap:
        name: config-files
        items:
          - key: node-api-server.toml
            path: node-api-server.toml